# Generated by Django 4.2 on 2024-08-09 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="Бренд")),
                ("model", models.CharField(max_length=100, verbose_name="Марка")),
                ("year", models.IntegerField(verbose_name="Год выпуска")),
                (
                    "fuel_type",
                    models.CharField(max_length=30, verbose_name="Тип топлива"),
                ),
                (
                    "transmission",
                    models.CharField(max_length=30, verbose_name="Тип КПП"),
                ),
                ("mileage", models.PositiveIntegerField(verbose_name="Пробег")),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "машина",
                "verbose_name_plural": "машины",
            },
        ),
    ]
