name: main

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2
        with:
          docker-version: '20.10.7'

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Create .env file for tests
        run: echo "ENV_STAGE=${{ secrets.ENV_STAGE }}" > .env

      - name: Build and run docker
        run: make run-test

      - name: Run tests
        run: make tests

      - name: Run linters
        run: make linters

      - name: Clean up
        run: make clean